services:
  - type: web
    name: flash-learning
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/app.py
    repo: https://github.com/daniellekotter/website-flashcards
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
