services:
  - type: web
    name: flash-learning
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    repo: https://github.com/daniellekotter/website-flashcards
    envVars:
      - key: PORT
        value: 8000
